#!/bin/sh

REDDDD='\033[0;31m'
DGREEN='\033[0;32m'
GREENN='\033[1;32m'
WHITEE='\033[0;37m'
BLUEEE='\033[1;34m'
CYANNN='\033[1;36m'
YELLOW='\033[1;33m'
NCCCCC='\033[0m' 

current_ip_configuration(){
    bold="\033[1m"
    yellow="\033[1;33m"
    green="\033[0;32m"
    red="\033[0;31m"
    reset="\033[0m"
    # Get a list of all network interfaces
    interfaces=$(ip link show | awk -F: '/^[0-9]+:/ {print $2}' | tr -d ' ')
    # Loop through each interface
    for iface in $interfaces; do
        # Get IP address and network details for the interface
        ip_info_v4=$(ip addr show dev $iface | awk '/inet / {print $2}' | tr -d '\n')
        ip_info_v6=$(ip addr show dev $iface | awk '/inet6 / {print $2}' | tr -d '\n')

        # Display network information for the interface
        echo "${bold}${yellow}Interface:${reset} $iface"
        echo "${bold}${yellow}IPv4 Address:${reset} $ip_info_v4"
        echo "${bold}${yellow}IPv6 Address:${reset} $ip_info_v6"
        echo
    done
    # Check internet connectivity
    ping -c 1 google.com > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "${bold}${yellow}Internet Status:${reset} ${green}Connected${reset}"
    else
        echo "${bold}${yellow}Internet Status:${reset} ${red}Disconnected${reset}"
    fi
    # Display DNS server information
    dns_servers=$(systemd-resolve --status | awk '/DNS Servers:/ {print $3}')
    echo "${bold}${yellow}DNS Servers:${reset} $dns_servers"
}

robot_status() {
    service_name="ros2"  # Update with your actual service name

    if systemctl is-active --quiet $service_name; then
        echo "${WHITEE}Robot Status:${DGREEN} Active ${NCCCCC}"
    else
        echo "${WHITEE}Robot Status:${REDDDD} Not Active ${NCCCCC}"
    fi
}

echo ${REDDDD}"-------------------------------------------------------------------------------"${WHITEE}
neofetch
echo ${REDDDD}"-------------------------------------------------------------------------------"${WHITEE}
echo ${WHITEE}"                                                                               "${WHITEE}
echo ${YELLOW}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YELLOW}"Network Configuration                                                          "${WHITEE}
echo ${YELLOW}"-------------------------------------------------------------------------------"${WHITEE}
current_ip_configuration
echo ${YELLOW}"-------------------------------------------------------------------------------"${WHITEE}
echo ${WHITEE}"                                                                               "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"       _  _  _  _  ____   __  ____  ____  _  _   __  ____                      "${WHITEE}
echo ${GREENN}"      ( \/ )( \/ )(  _ \ /  \(_  _)/ ___)/ )( \ /  \(  _ \                     "${WHITEE}
echo ${GREENN}"      / \/ \ )  /  ) _ ((  O ) )(  \___ \) __ ((  O )) __/                     "${WHITEE}
echo ${GREENN}"      \_)(_/(__/  (____/ \__/ (__) (____/\_)(_/ \__/(__)                       "${WHITEE}
echo ${GREENN}"                                                                               "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
robot_status
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${WHITEE}"GO2 Pi IP:              192.168.123.161                                        "${WHITEE}
echo ${WHITEE}"                                                                               "${WHITEE}
echo ${WHITEE}"GO2 Nvidia IP:          192.168.123.18                                         "${WHITEE}
echo ${WHITEE}"Pswd:                   123                                                    "${WHITEE}
echo ${WHITEE}"SSH:                    ssh -X unitree@192.168.123.18                          "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"GO2 Startup                                                                    "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${WHITEE}"GO2 System Driver:   ros2 launch go2_bringup system.launch.py                  "${WHITEE}
echo ${WHITEE}"GO2 Visualuzation:   ros2 launch go2_viz view_robot.launch.py                  "${WHITEE}
echo ${WHITEE}"GO2 Teleoperation:   ros2 run teleop_twist_keyboard teleop_twist_keyboard      "${WHITEE}
echo ${WHITEE}"                                                                               "${WHITEE}
echo ${WHITEE}"GO2 Navi SLAM:       ros2 launch go2_navigation slam.launch.py                 "${WHITEE}
echo ${WHITEE}"GO2 Navi Odom:       ros2 launch go2_navigation odom_navi.launch.py            "${WHITEE}
echo ${WHITEE}"GO2 Navi Map:        ros2 launch go2_navigation map_navi.launch.py             "${WHITEE}
echo ${WHITEE}"                                                                               "${WHITEE}
echo ${WHITEE}"GO2 + Arm Driver:    ros2 launch go2_moveit system_openmanipulator.launch.py   "${WHITEE}
echo ${WHITEE}"GO2 Arm Moveit:      ros2 launch go2_manipulation system.launch.py             "${WHITEE}
echo ${WHITEE}"                                                                               "${WHITEE}
echo ${WHITEE}"Rebuild package:     colcon build --symlink-install                            "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}