#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Software License Agreement (BSD)
#
# @author    Salman Omar Sohail <support@mybotshop.de>
# @copyright (c) 2024, MYBOTSHOP GmbH, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of MYBOTSHOP GmbH nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of MYBOTSHOP GmbH.


import gi
gi.require_version('Gst', '1.0')
import rclpy
import time
import numpy as np
import threading

from gi.repository import Gst, GLib
from cv_bridge import CvBridge
from rclpy.node import Node
from sensor_msgs.msg import Image
from unitree_go.msg import SportModeState

class Go2Camera(Node):
    def __init__(self):
        super().__init__('go2_camerapublisher')

        # URDF
        self.robot_camera_link = 'base_link'

        # Camera Data
        self.picture_height  = 720
        self.picture_width   = 1280
        self.picture_step    = 720 
        self.picture_encoding= 'rgb8'

        # Flags
        self.camera_data    = 0 
        self.camera_state = None 

        # Parameters
        self.declare_parameters(namespace='', parameters=[('lan_port',None)])

        self.param_lan_port = self.get_parameter('lan_port').value

        # Publishers
        self.publisher_camera = self.create_publisher(Image, 'sensor/camera', 10)
        self.pub_camera_data_image = Image()

        # Timer to periodically trigger the GStreamer callback
        self.create_subscription(SportModeState, '/sportmodestate', self.callback_video, 1)
        self.rate = self.create_rate(10) 

        # Camera Capture
        Gst.init(None) # GStreamer pipeline string
        gstreamer_str = f"udpsrc address=230.1.1.1 port=1720 multicast-iface={self.param_lan_port} ! application/x-rtp, media=video, encoding-name=H264 ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! video/x-raw,width=1280,height=720,format=BGR ! appsink drop=1"
        self.pipeline = Gst.parse_launch(gstreamer_str) # Create GStreamer pipeline
        self.appsink = self.pipeline.get_by_name("appsink0") # Create an AppSink to get video frames
        self.appsink.set_property("emit-signals", True)
        self.appsink.set_property("max-buffers", 1)
        self.appsink.connect("new-sample", self.callback_camera) # Connect the callback function to the "new-sample" signal
        self.pipeline.set_state(Gst.State.PLAYING) # Start the GStreamer pipeline

        # Track Startup
        self.startup_time = time.time()
        self.startup_wait = 3.0

    def colorize(self, text, color):
        color_codes = {
            'green': '\033[92m',
            'yellow': '\033[93m',
            'orange': '\033[38;5;208m', 
            'blue': '\033[94m',
            'red': '\033[91m'
        }
        return color_codes[color] + text + '\033[0m'

    def callback_video(self, data):
        pass

    def callback_camera(self, sink):
        sample = sink.emit("pull-sample")
        buffer = sample.get_buffer()
        success, map_info = buffer.map(Gst.MapFlags.READ) # Map the buffer to a readable memory format
        if not success:
            self.get_logger().error(f'{self.colorize("Camera Error: Failed to map buffer","red")}', throttle_duration_sec=5)
            return Gst.FlowReturn.ERROR        
        data = np.frombuffer(map_info.data, dtype=np.uint8) # Extract the frame data as bytes
        buffer.unmap(map_info) # Unmap the buffer
        frame = np.reshape(data, (720, 1280, 3)) # Reshape the data to an OpenCV image
        self.camera_state = CvBridge().cv2_to_imgmsg(frame, encoding="bgr8")
        return Gst.FlowReturn.OK
        
    def update_camera_image(self):
        if self.camera_state is not None: 
            self.pub_camera_data_image.header.stamp = self.get_clock().now().to_msg()
            self.pub_camera_data_image.header.frame_id = self.robot_camera_link
            self.pub_camera_data_image.height = self.picture_height
            self.pub_camera_data_image.width = self.picture_width
            self.pub_camera_data_image.encoding = self.picture_encoding
            self.pub_camera_data_image.is_bigendian = False
            self.pub_camera_data_image.step = self.picture_step 
            pixel_values = list(self.camera_state.data)
            self.pub_camera_data_image.data = pixel_values
            self.publisher_camera.publish(self.pub_camera_data_image)
            self.get_logger().info(f'{self.colorize("GO2 Camera Data Received","green")}', once=True)
        else:
            if time.time() - self.startup_time > self.startup_wait:
                self.get_logger().error(f'{self.colorize("No GO2 Camera Data Received","orange")}', throttle_duration_sec=5)
 
    def destroy_node(self):
        self.get_logger().info(f'{self.colorize("GO2 Camera Publisher is shutting down","red")}')
        if hasattr(self, 'pipeline') and self.pipeline is not None:
            self.pipeline.set_state(Gst.State.NULL)

        super().destroy_node() 
        
def main(args=None):
    rclpy.init(args=args)
    robot = Go2Camera()

    thread_node = threading.Thread(target=rclpy.spin, args=(robot, ), daemon=True)
    thread_node.start()      

    try:
        while rclpy.ok():
            robot.update_camera_image()
            robot.rate.sleep()

    except KeyboardInterrupt:
        pass
    finally:
        robot.destroy_node()
        rclpy.shutdown()
        thread_node.join()

if __name__ == '__main__':
    main()
